<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <UseWpf>true</UseWpf>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>neo_bpsys_wpf.SamplePlugin</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../neo-bpsys-wpf.Core/neo-bpsys-wpf.Core.csproj" />
    <PackageReference Include="WPF-UI" Version="4.0.3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.9" />
  </ItemGroup>

</Project>
